version: "3.8"
services:
  web:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    environment:
      NODE_ENV: production
      PORT: 3000
      MONGODB_URI: mongodb://mongo:27017/mydb

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  mongo-express:
    image: mongo-express:latest
    ports:
      - "8081:8081"
    depends_on:
      - mongo
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: rohan
      ME_CONFIG_MONGODB_ADMINPASSWORD: rohan
      ME_CONFIG_MONGODB_URL: mongodb://mongo:27017/

volumes:
  mongo-data:
