import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbaar_componets from "./Componets/Navbaar";
import Footer_componets from "./Componets/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${geistSans.variable} ${geistMono.variable}`}>
      <body>
        
        <Navbaar_componets/>
        {children}
        <Footer_componets/>
        

        
        </body>
    </html>
  );
}
